# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0921f235443a169c96342760574a1dc447f551c2a393e4af040029fc3df76a6159a6acb2500f11e927d034fe688ed97ca25ca77723b077c2362511ea2f2523a6

test:
  secret_key_base: 22aba7b256309702d0bd54b3583dfe7d0f2d45418bb4cc690686a0096ab3de513e710bf7f2c4d5aacadb7039011bd515248aa5c80a218836733f44dcbf5c6138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
